### ISSUE TITLE
Provide a version of task::park() that doesn't panic

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/futures-rs#235] opened 2016-11-05 22:53 UTC
When implementing abstractions on top of tasks, if a call to `task::park()` will panic, it is sometimes important to be able to perform some cleanup work. Right now, it isn't possible to do that.

Either a fn to test if currently running on on a task or have park() -> Option would do.

**Comment by liran-ringel** [comment] 2016-11-05 22:59
Why not doing clean with RAII using `Drop`?

**Comment by carllerche** [comment] 2016-11-07 20:06
It would take additional fields in the struct (making it a larger struct) to track enough state to remember where the panic happened and how to clean up.

**Comment by alexcrichton** [comment] 2016-11-11 00:24
I'm going to close this as a dupe of https://github.com/alexcrichton/futures-rs/issues/131 (as that's basically what it'd be)

**Closed by alexcrichton** 2016-11-11 00:24 UTC
