### ISSUE TITLE
Suggestion: Replace Result<Async<T>, E> with Async<T, E>

### ISSUE THREAD

**Issue by nicoburns** [alexcrichton/futures-rs#533] opened 2017-07-10 13:58 UTC
I have just read this article: https://www.coredump.ch/2017/07/05/understanding-the-tokio-reactor-core/ and the double wrapping of future return values (e.g. `return Ok(Async::Ready(self.answer))`) looks pretty cumbersome to me.

My suggestion is to add an `Err` variant to the `futures::Async` enum (and rename `Ready` to `Ok`) so that it becomes:

```rust
pub enum Async<T, E> {
    Ok(T),
    Err(E),
    NotReady,
}
```

Then `Ok(Async::Ready(self.answer))` can simply become `Async::Ok(self.answer)`.

**Comment by alexcrichton** [comment] 2017-07-10 14:23
Thanks for the report! I believe this is a duplicate of https://github.com/alexcrichton/futures-rs/issues/141 which has been closed, so I'm going to close this as well.

**Closed by alexcrichton** 2017-07-10 14:23 UTC
