### ISSUE TITLE
MPSC: Send unless blocks

### ISSUE THREAD

**Issue by golddranks** [alexcrichton/futures-rs#478] opened 2017-05-17 09:08 UTC
Using a bounded MPSC channel, would it be possible to send conditionally on the condition that the channel won't block?

Something like: `futures::unsync::mpsc::Sender::send_unless_blocks(&mut self, item: Self::SinkItem) -> Result<(), WouldBlock>`.

Here's my motivation for such an API: I want to send a `Task` handler from a stream that's going to be parked, to an outer receiver that's going to unpark it, but I don't want to send it multiple times in the case the stream is polled multiple times: if the stream won't block, I want to sent the `Task` and return an `Async::NotReady`. If the stream would block, that means that the stream isn't unparked yet, so I want just to return an `Async::NotReady`.

**Comment by carllerche** [comment] 2017-05-17 17:14
Yes, I would like a `try_send` API. Related to https://github.com/alexcrichton/futures-rs/issues/389

**Comment by alexcrichton** [comment] 2017-05-18 16:57
I'm gonna close this in favor of https://github.com/alexcrichton/futures-rs/issues/256 as I think this is mostly a duplicate of that. That being said I'm totally fine doing this whenever! Sounds like `mpsc::Sender` is a "special enough" use case that it warrants an extra API here not on `Sink` itself.

**Comment by carllerche** [comment] 2017-05-18 16:59
This is similar but different. The other issue proposes an API that will
notify you when the queue is ready (requires being run on a task). This
issue requests an API that can be run off task.

**Comment by carllerche** [comment] 2017-05-18 17:00
Reopening for now. Can close again if we want #256 to represent both apis.

**Comment by alexcrichton** [comment] 2017-08-24 15:07
Hm this accidentally landed somehow...

**Closed** 2017-09-12 04:23 UTC
