### ISSUE TITLE
Panic when "forgetting" ReadTask.

### ISSUE THREAD

**Issue by Antti** [alexcrichton/futures-rs#70] opened 2016-08-17 15:02 UTC
When experimenting with futures and task, I got the weird panic:
```
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `4567965872`, right: `4567966032`)', /Users/admytrenko/.cargo/git/checkouts/futures-rs-a4f11d094efefb0a/master/src/task.rs:202
...
  7:        0x10fc46e01 - futures::task::Task::get::h11c78cea13602c1a
   8:        0x10fc44056 - _<futures_io..task..TaskIoTake<'a, 'b, T>>::new::h733b3b84a5e2dd45
   9:        0x10fc460b6 - _<futures_io..task..TaskIoRead<T> as futures_io..ReadTask>::read::h8e19612329de43fb
  10:        0x10fc4a451 - _<futures_io..read_exact..ReadExact<A, T> as futures..Future>::poll::ha3f0ac7f0692a919
```

I understand, that "forgetting" task here probably does not make much sense, but "safe" rust should not panic unless I'm calling some functions that may panic (unwrap, etc).

futures-rs version: https://github.com/alexcrichton/futures-rs/commit/f6729636520f313c0e1f420329c1e2f19aba826c  (latest master at this time).
The smallest example I came up with, which crashes when you try to connect to the server:

```rust
extern crate futures;
extern crate futures_io;
extern crate futures_mio;

use std::env;
use std::net::SocketAddr;

use futures::Future;
use futures_io::{copy, TaskIo, read_exact, write_all};
use futures::stream::Stream;

fn main() {
    let addr = env::args().nth(1).unwrap_or("127.0.0.1:8080".to_string());
    let addr = addr.parse::<SocketAddr>().unwrap();
    let mut l = futures_mio::Loop::new().unwrap();
    let server = l.handle().tcp_listen(&addr);
    let done = server.and_then(move |socket| {
        // Once we've got the TCP listener, inform that we have it
        println!("Listening on: {}", addr);
        socket.incoming().for_each(|(socket, addr)| {
            let io = TaskIo::new(socket);
            let pair = io.map(|io| io.split());
            let amt = pair.map(|(reader, writer)| {
                read_exact(reader, vec![0; 1]).forget()
            }).forget();
            Ok(())
        })
    });
    l.run(done).unwrap();
}
```

**Comment by alexcrichton** [comment] 2016-08-17 18:01
Thanks for the report! The cause here is that a `TaskData` will panic if accessed with the wrong task. For each connection in this example, there's three tasks in play. One is the task which is driving the acceptance of new sockets. Another is the task for each socket with `pair.map(...).forget()`. The final one is the `read_exact(..).forget()`.

The `TaskIo` structure binds the I/O to one particular task, and it will panic if used with another task. Here it's bound to the second task, `pair.map(..).forget()`, but then when used with `read_exact(..).forget()` it panics.

The fix here is to change the final `map` to an `and_then` as well as removing the `.forget()` on the `read_exact`. Does that make sense?

**Comment by Antti** [comment] 2016-08-17 19:01
@alexcrichton I managed to make it work (in a similar way to what you suggested), by following the "echo.rs" example more closely.
Is it possible to encode TaskData relations on the type level, so that the given example won't compile, rather then panicking on the runtime?

**Comment by alexcrichton** [comment] 2016-08-17 21:54
Unfortunately we don't have a great way of doing that that doesn't hinder the ergonomics to the point of making it unusable :(

**Comment by alexcrichton** [comment] 2016-08-18 15:35
For now I'm going to close this as intended behavior, but let me know if you need any help!

**Closed by alexcrichton** 2016-08-18 15:35 UTC
