### ISSUE TITLE
Generic `Stream::collect()`?

### ISSUE THREAD

**Issue by partim** [alexcrichton/futures-rs#467] opened 2017-05-06 09:08 UTC
`Stream::collect()` currently collects all `Item`s into a `Vec<Item>` in notable difference to `Iterator::collect()` which allows to specify the target type. Perhaps it would make sense to follow `Iterator`’s lead and have a version of collect somewhat like this:

```rust
pub trait Stream {
    // ...
    fn collect<B: FromStream<Self::Item, Self::Error>>(self) -> B;
}

pub trait FromStream<A, E> {
    fn from_stream<S: Stream<Item=A, Error=E>(stream: S) -> Self;
}
```

**Comment by stepancheg** [comment] 2017-05-07 21:28
In 99% cases, collect to `Vec` is enough. And for the rest of cases, you can manually do `fold`.

But if `collect` will be generic, you would need to explicitly specify type parameters too often. E. g. this code:

```
println("{:?}", stream.collect());
```

will not work after this change.

**Comment by partim** [comment] 2017-05-08 09:45
You are certainly correct, but the same argument applies to `Iterator`, too. While I personally would prefer `Stream` and `Iterator` to have semantically similar interfaces, sticking a note to `Stream::collect()`’s documentation pointing to `fold()` would certainly be enough.

**Comment by alexcrichton** [comment] 2017-05-08 14:18
Thanks for the report! I'd definitely love to have this be generic as well, it's definitely more fitting for the standard library. I agree with @stepancheg that most of the time you collect to a `Vec`, but idiomatically from the standard library it's expected to be able to collect into any collection.

I don't think a `FromStream` trait is quite what we want though as it's a little too abstract I think. I'm thinking that we'd ideally work with a `FromIterator` bound (of some form) but unfortunately I'm not sure there's a great way to do that. We otherwise don't have a great trait for creating a collection other than `Default + Extend` which sort of works for `unzip` in the standard library.

In any case this is a breaking change for 0.1, so it'll need to be delayed to 0.2 in any case.

**Comment by ishitatsuyuki** [comment] 2017-05-19 13:22
Merge with #396?

**Comment by alexcrichton** [comment] 2017-05-19 15:01
Ah yes, a duplicate of https://github.com/alexcrichton/futures-rs/issues/396

**Closed by alexcrichton** 2017-05-19 15:01 UTC
Labels: 0.2-cleanup
